# Basic configuration for a GitHub Pages site

# Site settings
title: Your Site Title
description: A brief description of your site
url: "https://yourusername.github.io" # Your GitHub Pages URL
baseurl: "" # Set to "" for root of the repository, or "/repositoryname" if your site is hosted in a subdirectory

# Build settings
theme: jekyll-theme-cayman # You can choose any available GitHub Pages theme
markdown: kramdown # The Markdown processor
