# Basic configuration for a GitHub Pages site

# Site settings
title: antaresalphatest
description: antaresalphatest
url: "https://binarystone.github.io/antaresalphatest/" # Your GitHub Pages URL
baseurl: ""
theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0
