# Basic configuration for a GitHub Pages site

# Site settings
title: antaresalphatest
description: antaresalphatest
url: "https://antaresalphatest.github.io" # Your GitHub Pages URL
baseurl: ""

# Build settings
theme: jekyll-theme-cayman # You can choose any available GitHub Pages theme
markdown: kramdown # The Markdown processor
