# Basic configuration for a GitHub Pages site

# Site settings
title: antaresalphatest
description: antaresalphatest
url: "https://antaresalphatest.github.io" # Your GitHub Pages URL
baseurl: ""

# Build settings
# markdown: kramdown # The Markdown processor
remote_theme: pages-themes/time-machine@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
